table DimAccount
	lineageTag: d0000003-0000-0000-0000-000000000001

	column Konto
		dataType: int64
		isKey
		lineageTag: d0000003-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: Konto

	column Kontonavn
		dataType: string
		lineageTag: d0000003-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: Kontonavn

	column Kontotype
		dataType: string
		lineageTag: d0000003-0000-0000-0000-000000000007
		summarizeBy: none
		sourceColumn: Kontotype

	column SRS_regnskapslinje
		dataType: string
		lineageTag: d0000003-0000-0000-0000-000000000008
		summarizeBy: none
		sourceColumn: SRS_regnskapslinje

	column StandardKonto3
		dataType: int64
		lineageTag: d0000003-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: StandardKonto3

	column Kontoklasse
		dataType: int64
		lineageTag: d0000003-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: Kontoklasse

	column Kontogruppe
		dataType: int64
		lineageTag: d0000003-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: Kontogruppe

	column AktuellFor
		dataType: string
		lineageTag: d0000003-0000-0000-0000-000000000009
		summarizeBy: none
		sourceColumn: AktuellFor

	hierarchy Kontohierarki
		lineageTag: d0000003-0000-0000-0000-000000000010

		level SRS_regnskapslinje
			lineageTag: d0000003-0000-0000-0000-000000000011
			column: SRS_regnskapslinje

		level Kontotype
			lineageTag: d0000003-0000-0000-0000-000000000012
			column: Kontotype

		level Kontonavn
			lineageTag: d0000003-0000-0000-0000-000000000013
			column: Kontonavn

		level Konto
			lineageTag: d0000003-0000-0000-0000-000000000014
			column: Konto

	partition DimAccount = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "DimAccount.csv"), [Delimiter=";", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Konto", Int64.Type}, {"StandardKonto3", Int64.Type}, {"Kontonavn", type text}, {"Kontoklasse", Int64.Type}, {"Kontogruppe", Int64.Type}, {"Kontotype", type text}, {"SRS_regnskapslinje", type text}, {"AktuellFor", type text}}, "en-US")
				in
				    #"Changed Type"

