table DimDate
	lineageTag: d0000001-0000-0000-0000-000000000001
	dataCategory: Time

	column Dato
		dataType: dateTime
		isKey
		formatString: yyyy-MM-dd
		lineageTag: d0000001-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: Dato

	column DatoNokkel
		dataType: int64
		lineageTag: d0000001-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: DatoNokkel

	column Aar
		dataType: int64
		lineageTag: d0000001-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: Aar

	column Kvartal
		dataType: string
		lineageTag: d0000001-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: Kvartal

	column MaanedNr
		dataType: int64
		lineageTag: d0000001-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: MaanedNr

	column AarMaaned
		dataType: string
		lineageTag: d0000001-0000-0000-0000-000000000007
		summarizeBy: none
		sourceColumn: AarMaaned
		sortByColumn: MaanedStart

	column MaanedStart
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: d0000001-0000-0000-0000-000000000008
		summarizeBy: none
		sourceColumn: MaanedStart

	hierarchy Tid
		lineageTag: d0000001-0000-0000-0000-000000000009

		level Aar
			lineageTag: d0000001-0000-0000-0000-000000000010
			column: Aar

		level Kvartal
			lineageTag: d0000001-0000-0000-0000-000000000011
			column: Kvartal

		level AarMaaned
			lineageTag: d0000001-0000-0000-0000-000000000012
			column: AarMaaned

		level Dato
			lineageTag: d0000001-0000-0000-0000-000000000013
			column: Dato

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "DimDate.csv"), [Delimiter=";", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Dato", type date}, {"DatoNokkel", Int64.Type}, {"Aar", Int64.Type}, {"Kvartal", type text}, {"MaanedNr", Int64.Type}, {"AarMaaned", type text}, {"MaanedStart", type date}})
				in
				    #"Changed Type"

