table DimForecastVersion
	lineageTag: d0000005-0000-0000-0000-000000000001

	column Versjon
		dataType: string
		isKey
		lineageTag: d0000005-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: Versjon

	column Versjonsnavn
		dataType: string
		lineageTag: d0000005-0000-0000-0000-000000000003
		sortByColumn: Sortering
		summarizeBy: none
		sourceColumn: Versjonsnavn

	column Sortering
		dataType: int64
		lineageTag: d0000005-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: Sortering

	partition DimForecastVersion = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "DimForecastVersion.csv"), [Delimiter=";", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Versjon", type text}, {"Versjonsnavn", type text}, {"Sortering", Int64.Type}}, "en-US")
				in
				    #"Changed Type"
