table DimOrganization
	lineageTag: d0000002-0000-0000-0000-000000000001

	column Organisasjonsnokkel
		dataType: string
		isKey
		lineageTag: d0000002-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: Organisasjonsnokkel

	column Institutt
		dataType: string
		lineageTag: d0000002-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: Institutt

	column Instituttnavn
		dataType: string
		lineageTag: d0000002-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: Instituttnavn

	column Koststed
		dataType: string
		lineageTag: d0000002-0000-0000-0000-000000000007
		summarizeBy: none
		sourceColumn: Koststed

	column Koststednavn
		dataType: string
		lineageTag: d0000002-0000-0000-0000-000000000008
		summarizeBy: none
		sourceColumn: Koststednavn

	column Koststedtype
		dataType: string
		lineageTag: d0000002-0000-0000-0000-000000000009
		summarizeBy: none
		sourceColumn: Koststedtype

	column Fakultet
		dataType: string
		lineageTag: d0000002-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: Fakultet

	column Fakultetsnavn
		dataType: string
		lineageTag: d0000002-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: Fakultetsnavn

	hierarchy 'Organisasjonshierarki'
		lineageTag: d0000002-0000-0000-0000-000000000010

		level Fakultetsnavn
			lineageTag: d0000002-0000-0000-0000-000000000011
			column: Fakultetsnavn

		level Instituttnavn
			lineageTag: d0000002-0000-0000-0000-000000000012
			column: Instituttnavn

		level Koststednavn
			lineageTag: d0000002-0000-0000-0000-000000000013
			column: Koststednavn

	partition DimOrganization = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "DimOrganization.csv"), [Delimiter=";", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Organisasjonsnokkel", type text}, {"Fakultet", type text}, {"Fakultetsnavn", type text}, {"Institutt", type text}, {"Instituttnavn", type text}, {"Koststed", type text}, {"Koststednavn", type text}, {"Koststedtype", type text}}, "en-US")
				in
				    #"Changed Type"

