table DimPositionGroup
	lineageTag: d0000006-0000-0000-0000-000000000001

	column Stillingsgruppe
		dataType: string
		isKey
		lineageTag: d0000006-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: Stillingsgruppe

	column Stillingsgruppenavn
		dataType: string
		lineageTag: d0000006-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: Stillingsgruppenavn

	column Stillingskategori
		dataType: string
		lineageTag: d0000006-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: Stillingskategori

	partition DimPositionGroup = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "DimPositionGroup.csv"), [Delimiter=";", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Stillingsgruppe", type text}, {"Stillingsgruppenavn", type text}, {"Stillingskategori", type text}}, "en-US")
				in
				    #"Changed Type"
