table DimProject
	lineageTag: d0000004-0000-0000-0000-000000000001

	column Prosjekt
		dataType: string
		isKey
		lineageTag: d0000004-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: Prosjekt

	column Prosjektnavn
		dataType: string
		lineageTag: d0000004-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: Prosjektnavn

	column Finansieringstype
		dataType: string
		lineageTag: d0000004-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: Finansieringstype

	column Finansieringskilde
		dataType: string
		lineageTag: d0000004-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: Finansieringskilde

	column Prosjektkategori
		dataType: string
		lineageTag: d0000004-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: Prosjektkategori

	hierarchy Prosjekthierarki
		lineageTag: d0000004-0000-0000-0000-000000000007

		level Finansieringstype
			lineageTag: d0000004-0000-0000-0000-000000000008
			column: Finansieringstype

		level Finansieringskilde
			lineageTag: d0000004-0000-0000-0000-000000000009
			column: Finansieringskilde

		level Prosjektkategori
			lineageTag: d0000004-0000-0000-0000-000000000010
			column: Prosjektkategori

		level Prosjektnavn
			lineageTag: d0000004-0000-0000-0000-000000000011
			column: Prosjektnavn

	partition DimProject = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "DimProject.csv"), [Delimiter=";", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Prosjekt", type text}, {"Prosjektnavn", type text}, {"Finansieringstype", type text}, {"Finansieringskilde", type text}, {"Prosjektkategori", type text}})
				in
				    #"Changed Type"
