table DimStudyProgram
	lineageTag: d0000007-0000-0000-0000-000000000001

	column Studieprogram
		dataType: string
		isKey
		lineageTag: d0000007-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: Studieprogram

	column Studieprogramnavn
		dataType: string
		lineageTag: d0000007-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: Studieprogramnavn

	column Studienivaa
		dataType: string
		lineageTag: d0000007-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: Studienivaa

	column NormerteStudiepoeng
		dataType: int64
		lineageTag: d0000007-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: NormerteStudiepoeng

	column Institutt
		dataType: string
		lineageTag: d0000007-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: Institutt

	column Fakultet
		dataType: string
		lineageTag: d0000007-0000-0000-0000-000000000007
		summarizeBy: none
		sourceColumn: Fakultet

	hierarchy Studie
		lineageTag: d0000007-0000-0000-0000-000000000008

		level Studienivaa
			lineageTag: d0000007-0000-0000-0000-000000000009
			column: Studienivaa

		level Studieprogramnavn
			lineageTag: d0000007-0000-0000-0000-000000000010
			column: Studieprogramnavn

	partition DimStudyProgram = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "DimStudyProgram.csv"), [Delimiter=";", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Studieprogram", type text}, {"Studieprogramnavn", type text}, {"Studienivaa", type text}, {"NormerteStudiepoeng", Int64.Type}, {"Institutt", type text}, {"Fakultet", type text}})
				in
				    #"Changed Type"
