table FactForecast
	lineageTag: f0000003-0000-0000-0000-000000000001

	column DatoNokkel
		dataType: int64
		lineageTag: f0000003-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: DatoNokkel

	column Organisasjonsnokkel
		dataType: string
		lineageTag: f0000003-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: Organisasjonsnokkel

	column Konto
		dataType: int64
		lineageTag: f0000003-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: Konto

	column Prosjekt
		dataType: string
		lineageTag: f0000003-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: Prosjekt

	column Versjon
		dataType: string
		lineageTag: f0000003-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: Versjon

	column ForecastBelop
		dataType: decimal
		formatString: #,##0.00
		lineageTag: f0000003-0000-0000-0000-000000000007
		summarizeBy: sum
		sourceColumn: ForecastBelop

	column Datastatus
		dataType: string
		lineageTag: f0000003-0000-0000-0000-000000000008
		summarizeBy: none
		sourceColumn: Datastatus

	column Sannsynlighet
		dataType: double
		formatString: 0.0%
		lineageTag: f0000003-0000-0000-0000-000000000009
		summarizeBy: average
		sourceColumn: Sannsynlighet

	column Kommentar
		dataType: string
		lineageTag: f0000003-0000-0000-0000-000000000010
		summarizeBy: none
		sourceColumn: Kommentar

	partition FactForecast = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "FactForecast.csv"), [Delimiter=";", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"Organisasjonsnokkel", type text}, {"Konto", Int64.Type}, {"Prosjekt", type text}, {"Versjon", type text}, {"ForecastBelop", Currency.Type}, {"Datastatus", type text}, {"Sannsynlighet", type number}, {"Kommentar", type text}})
				in
				    #"Changed Type"
