table FactStudyPoints
	lineageTag: f0000005-0000-0000-0000-000000000001

	column DatoNokkel
		dataType: int64
		lineageTag: f0000005-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: DatoNokkel

	column Organisasjonsnokkel
		dataType: string
		lineageTag: f0000005-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: Organisasjonsnokkel

	column Studieprogram
		dataType: string
		lineageTag: f0000005-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: Studieprogram

	column RegistrerteStudenter
		dataType: int64
		lineageTag: f0000005-0000-0000-0000-000000000005
		summarizeBy: sum
		sourceColumn: RegistrerteStudenter

	column PlanlagteStudiepoeng
		dataType: int64
		lineageTag: f0000005-0000-0000-0000-000000000006
		summarizeBy: sum
		sourceColumn: PlanlagteStudiepoeng

	column AvlagteStudiepoeng
		dataType: decimal
		formatString: #,##0.0
		lineageTag: f0000005-0000-0000-0000-000000000007
		summarizeBy: sum
		sourceColumn: AvlagteStudiepoeng

	column SPE60
		dataType: decimal
		formatString: #,##0.00
		lineageTag: f0000005-0000-0000-0000-000000000008
		summarizeBy: sum
		sourceColumn: SPE60

	column BestattAndel
		dataType: double
		formatString: 0.0%
		lineageTag: f0000005-0000-0000-0000-000000000009
		summarizeBy: average
		sourceColumn: BestattAndel

	partition FactStudyPoints = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "FactStudyPoints.csv"), [Delimiter=";", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"Organisasjonsnokkel", type text}, {"Studieprogram", type text}, {"RegistrerteStudenter", Int64.Type}, {"PlanlagteStudiepoeng", Int64.Type}, {"AvlagteStudiepoeng", type number}, {"SPE60", type number}, {"BestattAndel", type number}}, "en-US")
				in
				    #"Changed Type"

