table FactGL
	lineageTag: f0000001-0000-0000-0000-000000000001

	column Bilag
		dataType: string
		lineageTag: f0000001-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: Bilag

	column DatoNokkel
		dataType: int64
		lineageTag: f0000001-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: DatoNokkel

	column Organisasjonsnokkel
		dataType: string
		lineageTag: f0000001-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: Organisasjonsnokkel

	column Konto
		dataType: int64
		lineageTag: f0000001-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: Konto

	column Prosjekt
		dataType: string
		lineageTag: f0000001-0000-0000-0000-000000000006
		summarizeBy: none
		sourceColumn: Prosjekt

	column Belop_signert
		dataType: decimal
		formatString: #,##0.00
		lineageTag: f0000001-0000-0000-0000-000000000007
		summarizeBy: sum
		sourceColumn: Belop_signert

	column Tekst
		dataType: string
		lineageTag: f0000001-0000-0000-0000-000000000008
		summarizeBy: none
		sourceColumn: Tekst

	column Datakilde
		dataType: string
		lineageTag: f0000001-0000-0000-0000-000000000009
		summarizeBy: none
		sourceColumn: Datakilde

	partition FactGL = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "FactGL.csv"), [Delimiter=";", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Bilag", type text}, {"DatoNokkel", Int64.Type}, {"Organisasjonsnokkel", type text}, {"Konto", Int64.Type}, {"Prosjekt", type text}, {"Belop_signert", Currency.Type}, {"Tekst", type text}, {"Datakilde", type text}})
				in
				    #"Changed Type"
