table FactFTE
	lineageTag: f0000004-0000-0000-0000-000000000001

	column DatoNokkel
		dataType: int64
		lineageTag: f0000004-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: DatoNokkel

	column Organisasjonsnokkel
		dataType: string
		lineageTag: f0000004-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: Organisasjonsnokkel

	column Stillingsgruppe
		dataType: string
		lineageTag: f0000004-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: Stillingsgruppe

	column Aarsverk
		dataType: double
		formatString: #,##0.00
		lineageTag: f0000004-0000-0000-0000-000000000005
		summarizeBy: sum
		sourceColumn: Aarsverk

	column FagligeAarsverk
		dataType: double
		formatString: #,##0.00
		lineageTag: f0000004-0000-0000-0000-000000000006
		summarizeBy: sum
		sourceColumn: FagligeAarsverk

	column Scenario
		dataType: string
		lineageTag: f0000004-0000-0000-0000-000000000007
		summarizeBy: none
		sourceColumn: Scenario

	partition FactFTE = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "FactFTE.csv"), [Delimiter=";", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"Organisasjonsnokkel", type text}, {"Stillingsgruppe", type text}, {"Aarsverk", type number}, {"FagligeAarsverk", type number}, {"Scenario", type text}}, "en-US")
				in
				    #"Changed Type"

