table FactBudget
	lineageTag: f0000002-0000-0000-0000-000000000001

	column DatoNokkel
		dataType: int64
		lineageTag: f0000002-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: DatoNokkel

	column Organisasjonsnokkel
		dataType: string
		lineageTag: f0000002-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: Organisasjonsnokkel

	column Konto
		dataType: int64
		lineageTag: f0000002-0000-0000-0000-000000000004
		summarizeBy: none
		sourceColumn: Konto

	column Prosjekt
		dataType: string
		lineageTag: f0000002-0000-0000-0000-000000000005
		summarizeBy: none
		sourceColumn: Prosjekt

	column BudsjettBelop
		dataType: decimal
		formatString: #,##0.00
		lineageTag: f0000002-0000-0000-0000-000000000006
		summarizeBy: sum
		sourceColumn: BudsjettBelop

	column Scenario
		dataType: string
		lineageTag: f0000002-0000-0000-0000-000000000007
		summarizeBy: none
		sourceColumn: Scenario

	partition FactBudget = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "FactBudget.csv"), [Delimiter=";", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"Organisasjonsnokkel", type text}, {"Konto", Int64.Type}, {"Prosjekt", type text}, {"BudsjettBelop", Currency.Type}, {"Scenario", type text}}, "en-US")
				in
				    #"Changed Type"

