table FactBudget
	lineageTag: f0000002-0000-0000-0000-000000000001

	column DatoNokkel
		dataType: int64
		sourceColumn: DatoNokkel
		summarizeBy: none

	column Organisasjonsnokkel
		dataType: int64
		sourceColumn: Organisasjonsnokkel
		summarizeBy: none

	column Konto
		dataType: int64
		sourceColumn: Konto
		summarizeBy: none

	column Prosjekt
		dataType: string
		sourceColumn: Prosjekt
		summarizeBy: none

	column BudsjettBelop
		dataType: double
		formatString: #,##0.00
		sourceColumn: BudsjettBelop
		summarizeBy: sum

	column Scenario
		dataType: string
		sourceColumn: Scenario
		summarizeBy: none

	partition FactBudget = m
		mode: import
		source = ```
			let
			    Source = Csv.Document(File.Contents(DataFolder & "FactBudget.csv"), [Delimiter=";", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
			    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DatoNokkel", Int64.Type}, {"Organisasjonsnokkel", Int64.Type}, {"Konto", Int64.Type}, {"Prosjekt", type text}, {"BudsjettBelop", type number}, {"Scenario", type text}})
			in
			    #"Changed Type"
			```
